name: "Primer-ejercicio"

on:
  push:
    branches: [master]

jobs:
    build:
      name: "Ejercicio-1"
      run-on: ubuntu-lastest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
        - run: npm ci
        - run: npm start

